/**
 * Seeds the BOBO PARIS catalogue, content and commercial rules.
 *
 *   node scripts/seed.mjs --sql    # print the SQL, apply it yourself
 *   node scripts/seed.mjs          # apply it via SUPABASE_SERVICE_ROLE_KEY
 *
 * The script is idempotent: every statement upserts on a natural key (slug,
 * sku, code), so running it twice changes nothing. It never deletes a product,
 * so re-seeding cannot wipe stock you have since corrected.
 *
 * Data lives in ../data/seed/*.mjs — see products.mjs for what is confirmed
 * from boboparis.com and what is seed copy.
 */
import { categories } from '../data/seed/categories.mjs';
import { collections } from '../data/seed/collections.mjs';
import { products, expandVariants } from '../data/seed/products.mjs';
import { shippingMethods, discounts, settings } from '../data/seed/commerce.mjs';
import { headerNavigation, footerNavigation } from '../data/seed/navigation.mjs';
import { pages } from '../data/seed/pages.mjs';

// --- SQL literals ------------------------------------------------------------

const q = (value) =>
  value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`;

const num = (value) => (value === null || value === undefined ? 'null' : String(value));
const bool = (value) => (value ? 'true' : 'false');
const json = (value) => (value === null || value === undefined ? 'null' : `${q(JSON.stringify(value))}::jsonb`);
const textArray = (values) =>
  values.length === 0 ? `'{}'::char(2)[]` : `ARRAY[${values.map(q).join(',')}]::char(2)[]`;

function buildSql() {
  const out = [];
  const say = (line) => out.push(line);
  const rows = (values) => values.join(',\n  ');

  say('-- Generated by scripts/seed.mjs. Do not edit by hand.');
  say('begin;');

  // --- Categories ------------------------------------------------------------
  // Two passes so a child always finds its parent, whatever the array order.
  say('\n-- Categories');
  for (const [pass, wanted] of [['roots', null], ['children', 'child']]) {
    const subset = categories.filter((c) => (wanted === null ? !c.parent : Boolean(c.parent)));
    if (subset.length === 0) continue;

    say(`-- ${pass}
insert into public.categories (slug, name, audience, parent_id, position, is_published)
select t.slug, t.name, t.audience::audience,
       (select id from public.categories p where p.slug = t.parent_slug),
       t.position, true
from (values
  ${rows(
    subset.map(
      (c) =>
        `(${q(c.slug)}, ${q(c.name)}, ${q(c.audience)}, ${q(c.parent)}, ${num(c.position)})`,
    ),
  )}
) as t(slug, name, audience, parent_slug, position)
on conflict (slug) do update set
  name = excluded.name, audience = excluded.audience, parent_id = excluded.parent_id,
  position = excluded.position, is_published = true;`);
  }

  // --- Collections -----------------------------------------------------------
  say(`\n-- Collections
insert into public.collections (slug, title, subtitle, story, description, cover_image_url, hero_image_url, position, is_published, is_featured, published_at)
values
  ${rows(
    collections.map(
      (c) =>
        `(${q(c.slug)}, ${q(c.title)}, ${q(c.subtitle)}, ${q(c.story)}, ${q(c.story)}, ` +
        `${q(`/media/collections/${c.slug}-cover.webp`)}, ${q(`/media/collections/${c.slug}-hero.webp`)}, ` +
        `${num(c.position)}, true, ${bool(c.featured)}, now())`,
    ),
  )}
on conflict (slug) do update set
  title = excluded.title, subtitle = excluded.subtitle, story = excluded.story,
  description = excluded.description, cover_image_url = excluded.cover_image_url,
  hero_image_url = excluded.hero_image_url, position = excluded.position,
  is_published = true, is_featured = excluded.is_featured;`);

  // --- Products --------------------------------------------------------------
  say(`\n-- Products
insert into public.products (
  slug, name, model_name, description, composition, care_guide, manufacturing, origin_country,
  category_id, audience, status, is_one_of_a_kind, is_new,
  base_price_cents, compare_at_price_cents, currency, size_guide, position, published_at,
  seo_title, seo_description
)
select t.slug, t.name, t.model_name, t.description, t.composition, t.care_guide,
       t.manufacturing, t.origin_country,
       (select id from public.categories c where c.slug = t.category_slug),
       t.audience::audience, 'active', t.one_of_a_kind, t.is_new,
       t.price_cents, t.compare_at_cents, 'EUR', t.size_guide, t.position, now(),
       t.name || ' — BOBO PARIS', left(t.description, 158)
from (values
  ${rows(
    products.map(
      (p) =>
        `(${q(p.slug)}, ${q(p.name)}, ${q(p.modelName)}, ${q(p.description)}, ${q(p.composition)}, ` +
        `${q(p.careGuide)}, ${q(p.manufacturing)}, ${q(p.originCountry)}, ${q(p.category)}, ` +
        `${q(p.audience)}, ${bool(p.isOneOfAKind)}, ${bool(p.isNew)}, ${num(p.priceCents)}, ` +
        `${num(p.compareAtPriceCents)}, ${json(p.sizeGuide)}, ${num(p.position)})`,
    ),
  )}
) as t(slug, name, model_name, description, composition, care_guide, manufacturing,
       origin_country, category_slug, audience, one_of_a_kind, is_new, price_cents,
       compare_at_cents, size_guide, position)
on conflict (slug) do update set
  name = excluded.name, model_name = excluded.model_name, description = excluded.description,
  composition = excluded.composition, care_guide = excluded.care_guide,
  manufacturing = excluded.manufacturing, origin_country = excluded.origin_country,
  category_id = excluded.category_id, audience = excluded.audience, status = 'active',
  is_one_of_a_kind = excluded.is_one_of_a_kind, is_new = excluded.is_new,
  base_price_cents = excluded.base_price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  size_guide = excluded.size_guide, position = excluded.position,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;`);

  // --- Variants --------------------------------------------------------------
  const allVariants = products.flatMap((product) =>
    expandVariants(product).map((variant) => ({ ...variant, productSlug: product.slug })),
  );

  say(`\n-- Variants (${allVariants.length})
insert into public.product_variants (product_id, sku, size, color_name, color_hex, position, is_active)
select (select id from public.products p where p.slug = t.product_slug),
       t.sku, t.size, t.color_name, t.color_hex, t.position, true
from (values
  ${rows(
    allVariants.map(
      (v) =>
        `(${q(v.productSlug)}, ${q(v.sku)}, ${q(v.size)}, ${q(v.colorName)}, ${q(v.colorHex)}, ${num(v.position)})`,
    ),
  )}
) as t(product_slug, sku, size, color_name, color_hex, position)
on conflict (sku) do update set
  size = excluded.size, color_name = excluded.color_name, color_hex = excluded.color_hex,
  position = excluded.position, is_active = true;`);

  // Opening stock, applied only to rows still at zero so a re-seed never
  // overwrites an inventory correction made in the admin.
  say(`\n-- Opening stock (placeholder quantities — replace with the real inventory)
update public.inventory i
   set quantity = t.stock
  from (values
  ${rows(allVariants.map((v) => `(${q(v.sku)}, ${num(v.stock)})`))}
) as t(sku, stock)
 where i.variant_id = (select id from public.product_variants v where v.sku = t.sku)
   and i.quantity = 0 and i.reserved = 0;`);

  // --- Images ----------------------------------------------------------------
  const images = [];
  for (const product of products) {
    const variants = expandVariants(product);
    let position = 0;
    for (const [index, color] of product.colors.entries()) {
      const anchorSku = variants.find((v) => v.colorName === color.name)?.sku ?? null;
      for (const shot of [1, 2]) {
        images.push({
          productSlug: product.slug,
          anchorSku,
          url: `/media/products/${product.slug}-${index + 1}-${shot}.webp`,
          alt: `${product.name}${product.colors.length > 1 ? ` — ${color.name}` : ''}`,
          position: position++,
        });
      }
    }
  }

  say(`\n-- Images (${images.length})
delete from public.product_images
 where product_id in (select id from public.products where slug in (${products.map((p) => q(p.slug)).join(', ')}));

insert into public.product_images (product_id, variant_id, url, alt, width, height, position)
select (select id from public.products p where p.slug = t.product_slug),
       (select id from public.product_variants v where v.sku = t.anchor_sku),
       t.url, t.alt, 1200, 1600, t.position
from (values
  ${rows(
    images.map(
      (i) =>
        `(${q(i.productSlug)}, ${q(i.anchorSku)}, ${q(i.url)}, ${q(i.alt)}, ${num(i.position)})`,
    ),
  )}
) as t(product_slug, anchor_sku, url, alt, position);`);

  // --- Collection membership -------------------------------------------------
  const membership = products.flatMap((product) =>
    (product.collections ?? []).map((slug, index) => ({
      collectionSlug: slug,
      productSlug: product.slug,
      position: index,
    })),
  );

  say(`\n-- Collection membership
insert into public.collection_products (collection_id, product_id, position)
select (select id from public.collections c where c.slug = t.collection_slug),
       (select id from public.products p where p.slug = t.product_slug),
       t.position
from (values
  ${rows(
    membership.map(
      (m) => `(${q(m.collectionSlug)}, ${q(m.productSlug)}, ${num(m.position)})`,
    ),
  )}
) as t(collection_slug, product_slug, position)
on conflict (collection_id, product_id) do update set position = excluded.position;`);

  // --- Cross-sell ------------------------------------------------------------
  say(`\n-- Recommendations: pieces that share a capsule
insert into public.product_recommendations (product_id, recommended_id, kind, position)
select a.product_id, b.product_id, 'similar',
       row_number() over (partition by a.product_id order by b.position)
from public.collection_products a
join public.collection_products b
  on b.collection_id = a.collection_id and b.product_id <> a.product_id
on conflict do nothing;`);

  // --- Shipping --------------------------------------------------------------
  say(`\n-- Shipping methods
insert into public.shipping_methods (code, name, description, country_codes, price_cents, free_above_cents, min_days, max_days, position, is_active)
values
  ${rows(
    shippingMethods.map(
      (m) =>
        `(${q(m.code)}, ${q(m.name)}, ${q(m.description)}, ${textArray(m.countryCodes)}, ` +
        `${num(m.priceCents)}, ${num(m.freeAboveCents)}, ${num(m.minDays)}, ${num(m.maxDays)}, ${num(m.position)}, true)`,
    ),
  )}
on conflict (code) do update set
  name = excluded.name, description = excluded.description, country_codes = excluded.country_codes,
  price_cents = excluded.price_cents, free_above_cents = excluded.free_above_cents,
  min_days = excluded.min_days, max_days = excluded.max_days, position = excluded.position;`);

  // --- Discounts -------------------------------------------------------------
  say('\n-- Discounts (seeded inactive: activating a code is a commercial decision)');
  for (const discount of discounts) {
    say(`insert into public.discounts (name, kind, value, min_subtotal_cents, is_active)
select ${q(discount.name)}, ${q(discount.kind)}::discount_kind, ${num(discount.value)}, ${num(discount.minSubtotalCents)}, ${bool(discount.isActive)}
where not exists (select 1 from public.discounts where name = ${q(discount.name)});

insert into public.discount_codes (discount_id, code)
select (select id from public.discounts where name = ${q(discount.name)} limit 1), code
from unnest(ARRAY[${discount.codes.map(q).join(',')}]) as code
on conflict (code) do nothing;`);
  }

  // --- Settings --------------------------------------------------------------
  say(`\n-- Settings
insert into public.settings (key, value, description)
values
  ${rows(settings.map((s) => `(${q(s.key)}, ${json(s.value)}, ${q(s.description)})`))}
on conflict (key) do update set value = excluded.value, description = excluded.description;`);

  // --- Navigation ------------------------------------------------------------
  // Rebuilt wholesale: menu entries have no natural key to upsert on.
  const navRows = [];
  const navChildren = [];
  for (const [location, items] of [
    ['header', headerNavigation],
    ['footer', footerNavigation],
  ]) {
    for (const [index, item] of items.entries()) {
      navRows.push(
        `(${q(location)}, ${q(item.label)}, ${q(item.href ?? null)}, ${q(item.image ?? null)}, ${num(index)}, true)`,
      );
      for (const [childIndex, child] of (item.children ?? []).entries()) {
        navChildren.push(
          `(${q(location)}, ${num(index)}, ${q(child.label)}, ${q(child.href ?? null)}, ${q(child.column ?? null)}, ${num(childIndex)})`,
        );
      }
    }
  }

  say(`\n-- Navigation
delete from public.navigation_items;

insert into public.navigation_items (location, label, href, image_url, position, is_published)
values
  ${rows(navRows)};

insert into public.navigation_items (location, parent_id, label, href, column_label, position, is_published)
select t.location,
       (select id from public.navigation_items n
         where n.location = t.location and n.parent_id is null and n.position = t.parent_position),
       t.label, t.href, t.column_label, t.position, true
from (values
  ${rows(navChildren)}
) as t(location, parent_position, label, href, column_label, position);`);

  // --- CMS pages -------------------------------------------------------------
  say(`\n-- Pages
insert into public.pages (slug, title, subtitle, seo_title, seo_description, is_published)
values
  ${rows(
    pages.map(
      (p) =>
        `(${q(p.slug)}, ${q(p.title)}, ${q(p.subtitle ?? null)}, ${q(p.seoTitle ?? null)}, ${q(p.seoDescription ?? null)}, true)`,
    ),
  )}
on conflict (slug) do update set
  title = excluded.title, subtitle = excluded.subtitle,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description, is_published = true;`);

  const sectionRows = pages.flatMap((page) =>
    page.sections.map(
      (section, index) =>
        `(${q(page.slug)}, ${q(section.kind)}, ${json(section.content)}, ${num(index)})`,
    ),
  );

  say(`\n-- Page sections (${sectionRows.length})
delete from public.page_sections
 where page_id in (select id from public.pages where slug in (${pages.map((p) => q(p.slug)).join(', ')}));

insert into public.page_sections (page_id, kind, content, position, is_published)
select (select id from public.pages p where p.slug = t.page_slug),
       t.kind::page_section_kind, t.content, t.position, true
from (values
  ${rows(sectionRows)}
) as t(page_slug, kind, content, position);`);

  say('\ncommit;');
  return out.join('\n');
}

// --- Entry point -------------------------------------------------------------

async function main() {
  const sql = buildSql();

  if (process.argv.includes('--sql')) {
    process.stdout.write(sql);
    return;
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.error(
      'Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to apply the seed,\n' +
        'or run with --sql to print it and apply it yourself.',
    );
    process.exit(1);
  }

  // Applied through a single SQL statement so the whole seed is one transaction.
  const response = await fetch(`${url}/rest/v1/rpc/exec_seed_sql`, {
    method: 'POST',
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ p_sql: sql }),
  });

  if (!response.ok) {
    console.error(`Seed failed (${response.status}): ${await response.text()}`);
    console.error(
      '\nThe helper function may be missing. Apply supabase/migrations/0011_seed_helper.sql first,\n' +
        'or run `node scripts/seed.mjs --sql` and paste the output into the SQL editor.',
    );
    process.exit(1);
  }

  console.log(
    `Seeded ${products.length} products, ` +
      `${products.reduce((n, p) => n + expandVariants(p).length, 0)} variants, ` +
      `${collections.length} collections, ${pages.length} pages.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
